server:
  port: 8080
spring:
  application:
    name: cloud-order-service
  cloud:
    consul:
      host: localhost
      discovery:
        service-name: ${spring.application.name}
      port: 8500

# 链路追踪
management:
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans
  tracing:
    sampling:
      probability: 1.0 # 采样率默认是 0.1，值越大收集越及时