server:
  port: 8080
spring:
  application:
    name: cloud-order-service
  cloud:
    consul:
      host: localhost
      discovery:
        service-name: ${spring.application.name}
      port: 8500
