version: "3.5"

services:
  seata-mysql:
    image: mysql:8.0
    container_name: seata-mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - 3307:3306
    volumes:
      - ./mysql/data:/var/lib/mysql
      - ./mysql/conf.d:/etc/mysql/conf.d
      - ./mysql/initdb:/docker-entrypoint-initdb.d
    networks:
      - mysql

  seata-server:
    image: seata:v2.0.0
    hostname: seata-server
    container_name: seata-server
    ports:
      - 8091:8091
      - 7091:7091
    environment:
      - SEATA_PORT=8091
    volumes:
      - ./config:/seata-server/resources
    expose:
      - 8091
      - 7091
    networks:
      - mysql

networks:
  mysql:
    name: mysql
    driver: bridge
