server:
  port: 9527

spring:
  application:
    name: cloud-gateway
  # spring consul
  cloud:
    consul:
      host: localhost
      discovery:
        service-name: ${spring.application.name}
        prefer-ip-address: true
      port: 8500
    gateway:
      routes:
        - id: cloud-payment-service_gateway # 路由的 Id，类似与 mysql 的主键，没有固定的要求但是要唯一，建议配合服务名
          # uri: http://localhost:8001 # 匹配后提供服务的路由地址
          uri: lb://cloud-payment-service
          predicates:
            - Path=/pay/gateway/get/** # 断言，路径相匹配的进行路由