version: "3.5"

services:
  haust-mysql:
    image: mysql:8.0
    container_name: haust-mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - 3306:3306
    volumes:
      - ./mysql/data:/var/lib/mysql
      - ./mysql/conf.d:/etc/mysql/conf.d
      - ./mysql/initdb:/docker-entrypoint-initdb.d
    networks:
      - mysql

  # nacos 是有状态的,需要连接mysql, 所以将nacos和mysql放在同一个network中
  nacos:
    image: nacos/nacos-server:v2.3.0-slim
    container_name: nacos
    depends_on:
      - haust-mysql
    ports:
      - 8848:8848
      - 9848:9848
      - 9849:9849
    environment:
      - JVM_XMS=512m
      - JVM_XMX=512m
      - MODE=standalone
      - PREFER_HOST_MODE=hostname
      - SPRING_DATASOURCE_PLATFORM=mysql
      - MYSQL_SERVICE_HOST=haust-mysql
      - MYSQL_SERVICE_DB_NAME=nacos
      - MYSQL_SERVICE_USER=root
      - MYSQL_SERVICE_PASSWORD=root
    volumes:
      - ./nacos/logs:/home/nacos/logs
    networks:
      - mysql
      - nacos

networks:
  mysql:
    name: mysql
    driver: bridge
  nacos:
    name: serviceDiscovery
    driver: bridge
