server:
  port: 8080
spring:
  application:
    name: cloud-consumer-openfeign-order
  cloud:
    consul:
      host: localhost
      discovery:
        service-name: ${spring.application.name}
        prefer-ip-address: true # 是否优先使用服务 IP 进行注册
      port: 8500
    openfeign:
      client:
        config:
          default:
#            默认的连接超时
            connect-timeout: 4000
#            默认的读取超市
            read-timeout: 4000
          cloud-payment-service: # 细粒度的会覆盖 default
#            为专属的服务设置超时时间
            connect-timeout: 4000
#            为专属的服务设置读取超时时间
            read-timeout: 4000
