server:
  port: 8080
spring:
  application:
    name: cloud-consumer-openfeign-order
  cloud:
    consul:
      host: localhost
      discovery:
        service-name: ${spring.application.name}
        prefer-ip-address: true # 是否优先使用服务 IP 进行注册
      port: 8500
    openfeign:
      client:
        config:
          default:
            # 默认的连接超时
            connect-timeout: 4000
            # 默认的读取超市
            read-timeout: 4000
          cloud-payment-service: # 细粒度的会覆盖 default
            # 为专属的服务设置超时时间
            connect-timeout: 4000
            # 为专属的服务设置读取超时时间
            read-timeout: 4000
      compression:
        request:
          enabled: true
          min-request-size: 2048 # 最小触发的压缩的大小
          mime-types: text/xml,application/xml,application/json # 触发压缩的类型
        response:
          enabled: true

      # Apache Httpclient5 配置开启
      httpclient:
        hc5:
          enabled: true